Create azure-pipelines_gradle.yml
whitesource-ft/ws-examples pull request #64
Opened 2022-01-20 12:19 UTC by lukebroganws

Added ADO CI/CD Gradle example yml

2022-01-20 12:33 UTC, tidharm commented on CI-CD/AzureDevOps/azure-pipelines_gradle.yml
> +    WS_ENABLEIMPACTANALYSIS: false
Consider removing. enableImpactAnalysis is set to false by default, this is redundant.

2022-01-20 12:35 UTC, tidharm commented on CI-CD/AzureDevOps/azure-pipelines_gradle.yml
> +    WS_GRADLE_DOWNLOADMISSINGDEPENDENCIES: false
Consider removing. downloadMissingDependencies is a maven resolver parameter, the gradle resolver doesn't have it AFAIK

2022-01-20 12:39 UTC, tidharm requested changes
See my comments for lines 36 and 40

2022-02-07 08:16 UTC, tabac-ws commented on CI-CD/AzureDevOps/azure-pipelines_gradle.yml
> +    tasks: 'assembleDebug'
Shouldn't be "build"?

2022-02-07 09:00 UTC, tabac-ws approved these changes

2022-02-07 09:01 UTC, tabac-ws reviewed
Can't approve - see Tidahr's comments

2022-02-07 12:03 UTC, tidharm approved these changes

2022-02-07 12:03 UTC, merged