Tidharm dev
whitesource-ft/ws-examples pull request #67
Opened 2022-02-03 11:15 UTC by tidharm

2022-02-03 17:02 UTC, lukebroganws approved these changes

2022-02-03 17:05 UTC, samq-ws requested changes
@tidharm can you add into the CI-CD readme how to use the new cache section of [CI-CD/GitLab/gitlab-maven-cached-ua.yml](https://github.com/whitesource-ft/ws-examples/pull/67/files#diff-82333f0550e3171d9c68260aadc23b8e63a82843ff9f6e7a06a1f29d1105c749)

2022-02-04 15:14 UTC, samq-ws commented on Scripts/README.md
> +See additional example for implementation within a build pipeline under [CI-CD](https://github.com/whitesource-ft/ws-examples/tree/main/CI-CD) (`*-cached-ua.yml`).
This link does not go to an example of how to implement caching

2022-02-10 04:54 UTC, samq-ws approved these changes

2022-02-10 04:54 UTC, merged